# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow_Gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(625, 397)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Called_BlobDetection = QtWidgets.QPushButton(self.centralwidget)
        self.Called_BlobDetection.setGeometry(QtCore.QRect(11, 67, 93, 28))
        self.Called_BlobDetection.setObjectName("Called_BlobDetection")
        self.Called_Video = QtWidgets.QPushButton(self.centralwidget)
        self.Called_Video.setGeometry(QtCore.QRect(11, 249, 93, 28))
        self.Called_Video.setObjectName("Called_Video")
        self.Called_EdgeDetection = QtWidgets.QPushButton(self.centralwidget)
        self.Called_EdgeDetection.setGeometry(QtCore.QRect(11, 158, 93, 28))
        self.Called_EdgeDetection.setObjectName("Called_EdgeDetection")
        self.Called_ImageFilter = QtWidgets.QPushButton(self.centralwidget)
        self.Called_ImageFilter.setGeometry(QtCore.QRect(150, 70, 93, 28))
        self.Called_ImageFilter.setObjectName("Called_ImageFilter")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 625, 26))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.menu_File.addAction(self.action_Open)
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Called_BlobDetection.setText(_translate("MainWindow", "BlobDetection"))
        self.Called_Video.setText(_translate("MainWindow", "Video"))
        self.Called_EdgeDetection.setText(_translate("MainWindow", "EdgeDetection"))
        self.Called_ImageFilter.setText(_translate("MainWindow", "Image Filter"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
