# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Contour\Qt_Contour.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Contour_Gui(object):
    def setupUi(self, Contour_Gui):
        Contour_Gui.setObjectName("Contour_Gui")
        Contour_Gui.resize(827, 558)
        self.Contour_groupBox = QtWidgets.QGroupBox(Contour_Gui)
        self.Contour_groupBox.setGeometry(QtCore.QRect(10, 50, 271, 151))
        self.Contour_groupBox.setObjectName("Contour_groupBox")
        self.ContourMode_label = QtWidgets.QLabel(self.Contour_groupBox)
        self.ContourMode_label.setGeometry(QtCore.QRect(20, 40, 47, 13))
        self.ContourMode_label.setObjectName("ContourMode_label")
        self.ContourMode_comboBox = QtWidgets.QComboBox(self.Contour_groupBox)
        self.ContourMode_comboBox.setGeometry(QtCore.QRect(100, 40, 121, 21))
        self.ContourMode_comboBox.setObjectName("ContourMode_comboBox")
        self.ContourMode_comboBox.addItem("")
        self.ContourMode_comboBox.addItem("")
        self.ContourMode_comboBox.addItem("")
        self.ContourMode_comboBox.addItem("")
        self.ContourMode_comboBox.addItem("")
        self.ContourMethod_comboBox = QtWidgets.QComboBox(self.Contour_groupBox)
        self.ContourMethod_comboBox.setGeometry(QtCore.QRect(100, 70, 121, 21))
        self.ContourMethod_comboBox.setObjectName("ContourMethod_comboBox")
        self.ContourMethod_comboBox.addItem("")
        self.ContourMethod_comboBox.addItem("")
        self.ContourMethod_comboBox.addItem("")
        self.ContourMethod_comboBox.addItem("")
        self.ContourMethod_label = QtWidgets.QLabel(self.Contour_groupBox)
        self.ContourMethod_label.setGeometry(QtCore.QRect(10, 60, 91, 41))
        self.ContourMethod_label.setObjectName("ContourMethod_label")
        self.FindContour_pushButton = QtWidgets.QPushButton(self.Contour_groupBox)
        self.FindContour_pushButton.setGeometry(QtCore.QRect(10, 110, 93, 28))
        self.FindContour_pushButton.setObjectName("FindContour_pushButton")

        self.retranslateUi(Contour_Gui)
        QtCore.QMetaObject.connectSlotsByName(Contour_Gui)

    def retranslateUi(self, Contour_Gui):
        _translate = QtCore.QCoreApplication.translate
        Contour_Gui.setWindowTitle(_translate("Contour_Gui", "Form"))
        self.Contour_groupBox.setTitle(_translate("Contour_Gui", "GroupBox"))
        self.ContourMode_label.setText(_translate("Contour_Gui", "Mode"))
        self.ContourMode_comboBox.setCurrentText(_translate("Contour_Gui", "RETR_LIST"))
        self.ContourMode_comboBox.setItemText(0, _translate("Contour_Gui", "RETR_EXTERNAL"))
        self.ContourMode_comboBox.setItemText(1, _translate("Contour_Gui", "RETR_LIST"))
        self.ContourMode_comboBox.setItemText(2, _translate("Contour_Gui", "RETR_CCOMP"))
        self.ContourMode_comboBox.setItemText(3, _translate("Contour_Gui", "RETR_TREE"))
        self.ContourMode_comboBox.setItemText(4, _translate("Contour_Gui", "RETR_FLOODFILL"))
        self.ContourMethod_comboBox.setCurrentText(_translate("Contour_Gui", "CHAIN_APPROX_SIMPLE"))
        self.ContourMethod_comboBox.setItemText(0, _translate("Contour_Gui", "CHAIN_APPROX_NONE"))
        self.ContourMethod_comboBox.setItemText(1, _translate("Contour_Gui", "CHAIN_APPROX_SIMPLE"))
        self.ContourMethod_comboBox.setItemText(2, _translate("Contour_Gui", "CHAIN_APPROX_TC89_L1"))
        self.ContourMethod_comboBox.setItemText(3, _translate("Contour_Gui", "CHAIN_APPROX_TC89_KCOS"))
        self.ContourMethod_label.setText(_translate("Contour_Gui", "Approx method"))
        self.FindContour_pushButton.setText(_translate("Contour_Gui", "FindContour"))
