# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ImageFilter\Qt_ImageFilter.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageFilter_Gui(object):
    def setupUi(self, ImageFilter_Gui):
        ImageFilter_Gui.setObjectName("ImageFilter_Gui")
        ImageFilter_Gui.resize(638, 370)
        self.groupBox = QtWidgets.QGroupBox(ImageFilter_Gui)
        self.groupBox.setGeometry(QtCore.QRect(20, 40, 191, 151))
        self.groupBox.setCheckable(True)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 161, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Kernelsize_label = QtWidgets.QLabel(self.layoutWidget)
        self.Kernelsize_label.setObjectName("Kernelsize_label")
        self.verticalLayout.addWidget(self.Kernelsize_label)
        self.SigmaX_label = QtWidgets.QLabel(self.layoutWidget)
        self.SigmaX_label.setObjectName("SigmaX_label")
        self.verticalLayout.addWidget(self.SigmaX_label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Kernelsize_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.Kernelsize_comboBox.setObjectName("Kernelsize_comboBox")
        self.Kernelsize_comboBox.addItem("")
        self.Kernelsize_comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.Kernelsize_comboBox)
        self.SigmaX_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.SigmaX_comboBox.setObjectName("SigmaX_comboBox")
        self.SigmaX_comboBox.addItem("")
        self.SigmaX_comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.SigmaX_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.GaussisanFilter_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.GaussisanFilter_pushButton.setGeometry(QtCore.QRect(40, 110, 93, 28))
        self.GaussisanFilter_pushButton.setObjectName("GaussisanFilter_pushButton")
        self.Medianfilter_groupBox = QtWidgets.QGroupBox(ImageFilter_Gui)
        self.Medianfilter_groupBox.setGeometry(QtCore.QRect(20, 220, 191, 111))
        self.Medianfilter_groupBox.setCheckable(True)
        self.Medianfilter_groupBox.setObjectName("Medianfilter_groupBox")
        self.MedianKernelsize_comboBox = QtWidgets.QComboBox(self.Medianfilter_groupBox)
        self.MedianKernelsize_comboBox.setGeometry(QtCore.QRect(80, 30, 74, 20))
        self.MedianKernelsize_comboBox.setObjectName("MedianKernelsize_comboBox")
        self.MedianKernelsize_comboBox.addItem("")
        self.MedianKernelsize_comboBox.addItem("")
        self.MedianKernelsize_label = QtWidgets.QLabel(self.Medianfilter_groupBox)
        self.MedianKernelsize_label.setGeometry(QtCore.QRect(10, 30, 74, 20))
        self.MedianKernelsize_label.setObjectName("MedianKernelsize_label")
        self.MedianFilter_pushButton = QtWidgets.QPushButton(self.Medianfilter_groupBox)
        self.MedianFilter_pushButton.setGeometry(QtCore.QRect(30, 70, 93, 28))
        self.MedianFilter_pushButton.setObjectName("MedianFilter_pushButton")
        self.LaplacianFilter_groupBox = QtWidgets.QGroupBox(ImageFilter_Gui)
        self.LaplacianFilter_groupBox.setGeometry(QtCore.QRect(240, 50, 241, 141))
        self.LaplacianFilter_groupBox.setCheckable(True)
        self.LaplacianFilter_groupBox.setObjectName("LaplacianFilter_groupBox")
        self.LaplacianFilter_pushButton = QtWidgets.QPushButton(self.LaplacianFilter_groupBox)
        self.LaplacianFilter_pushButton.setGeometry(QtCore.QRect(40, 90, 93, 28))
        self.LaplacianFilter_pushButton.setObjectName("LaplacianFilter_pushButton")

        self.retranslateUi(ImageFilter_Gui)
        QtCore.QMetaObject.connectSlotsByName(ImageFilter_Gui)

    def retranslateUi(self, ImageFilter_Gui):
        _translate = QtCore.QCoreApplication.translate
        ImageFilter_Gui.setWindowTitle(_translate("ImageFilter_Gui", "Form"))
        self.groupBox.setTitle(_translate("ImageFilter_Gui", "Gaussian Filter"))
        self.Kernelsize_label.setText(_translate("ImageFilter_Gui", "Kernel size"))
        self.SigmaX_label.setText(_translate("ImageFilter_Gui", "SigmaX"))
        self.Kernelsize_comboBox.setItemText(0, _translate("ImageFilter_Gui", "3"))
        self.Kernelsize_comboBox.setItemText(1, _translate("ImageFilter_Gui", "5"))
        self.SigmaX_comboBox.setItemText(0, _translate("ImageFilter_Gui", "3"))
        self.SigmaX_comboBox.setItemText(1, _translate("ImageFilter_Gui", "5"))
        self.GaussisanFilter_pushButton.setText(_translate("ImageFilter_Gui", "Run"))
        self.Medianfilter_groupBox.setTitle(_translate("ImageFilter_Gui", "Median filter"))
        self.MedianKernelsize_comboBox.setItemText(0, _translate("ImageFilter_Gui", "3"))
        self.MedianKernelsize_comboBox.setItemText(1, _translate("ImageFilter_Gui", "5"))
        self.MedianKernelsize_label.setText(_translate("ImageFilter_Gui", "Kernel size"))
        self.MedianFilter_pushButton.setText(_translate("ImageFilter_Gui", "Run"))
        self.LaplacianFilter_groupBox.setTitle(_translate("ImageFilter_Gui", "Laplacian Filter"))
        self.LaplacianFilter_pushButton.setText(_translate("ImageFilter_Gui", "Run"))
